add_newline = false

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[username]
style_user = "red bold"
show_always = false  # Only show on SSH or if root

[hostname]
style = "red bold"
ssh_only = true

[directory]
style = "blue"
truncate_to_repo = false

[git_branch]
format = "$branch"

[git_status]
format = "\\[$all_status$ahead_behind\\]"
conflicted = "conflict"
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↑${ahead_count}↓${behind_count}"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "x"

[nodejs]
format = " node\\[$version\\]"
detect_files = [".nvmrc", "package.json"]
detect_extensions = ["js", "ts", "jsx", "tsx"]
style = "bold cyan"

[shell]
disabled = true

[cmd_duration]
disabled = true
