add_newline = false

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[username]
style_user = "red bold"
show_always = false  # Only show on SSH or if root

[hostname]
style = "red bold"
ssh_only = true

[directory]
style = "green"
truncate_to_repo = false

[c]
format = '[$symbol($version(-$name) )]($style)'
symbol = "compiler:"
style = "dimmed"

[nodejs]
format = '[$symbol($version )]($style)'
symbol = "node:"
style = "dimmed"

# [git_branch]
# format = "$branch"
#
[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = "git:"
style = "dimmed"

[git_status]
# format = "\\[$all_status$ahead_behind\\]"
format = '([\($all_status$ahead_behind\)]($style) )'
style = "bold yellow"
# conflicted = "conflict"
# ahead = "↑${count}"
# behind = "↓${count}"
# diverged = "↑${ahead_count}↓${behind_count}"
# untracked = "?"
# modified = "!"
# staged = "+"
# renamed = "»"
# deleted = "x"
#
# [nodejs]
# format = " node\\[$version\\]"
# detect_files = [".nvmrc", "package.json"]
# detect_extensions = ["js", "ts", "jsx", "tsx"]
# style = "bold cyan"

[shell]
disabled = true

[cmd_duration]
disabled = true
